sudo: required

language: go

services:
    - docker

env:
  COMPOSE_VERSION: 1.5.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - make ci_test

after_script:
  - make ci_clean

notifications:
  email:
    on_success: change
    on_failure: always
